version: '3'

networks:
  main:

volumes: 
  media: {}

services:
  rabbitmq:
    hostname: rabbitmq
    container_name: rabbitmq
    image: rabbitmq:latest
    restart: on-failure
    networks:
      - main

  isaac: &isaac
    container_name: isaac
    hostname: isaac
    image: isaac-image
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    expose:
      - '4000'
    links:
      - rabbitmq:rabbitmq
    volumes:
      - .:/isaac
      - media:/isaac/static/media:Z
    networks:
     - main

  celery_worker:
    <<: *isaac
    container_name: celery_worker
    hostname: celery_worker
    command: celery -A isaac_project worker -l info
    ports: []
    image: isaac-image
    depends_on:
      - rabbitmq
    networks:
      - main
    restart: on-failure

  celery_beat:
    container_name: celery_beat
    image: isaac-image
    command: celery -A isaac_project beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    hostname: celery_beat
    depends_on:
      - rabbitmq
    restart: on-failure
    networks:
      - main

  celery_flower:
    container_name: celery_flower
    image: isaac-image
    command: sh -c "pip install flower && celery flower -A isaac_project --broker=amqp://rabbitmq:5672// --port=5555"
    hostname: celery_flower
    depends_on:
      - rabbitmq
    restart: on-failure
    ports: 
      - '5555:5555'
    networks:
      - main

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - .:/isaac
      - ./config/nginx/:/etc/nginx/conf.d/
    depends_on:
      - isaac
    restart: on-failure
    networks:
      - main
