# Generated by Django 3.1.2 on 2020-11-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0003_auto_20201109_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='procedure_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
