# Generated by Django 3.1.2 on 2020-11-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='부서'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dept_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='부서 코드'),
        ),
        migrations.AlterField(
            model_name='user',
            name='emp_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='사번'),
        ),
        migrations.AlterField(
            model_name='user',
            name='img_src',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Profile 이미지'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_member',
            field=models.BooleanField(default=False, verbose_name='Isaac 회원'),
        ),
        migrations.AlterField(
            model_name='user',
            name='kr_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='직책'),
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='직함'),
        ),
    ]
